name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilando no JAVA
      run: |
           cd src
           javac -cp . Main.java
           javac -cp . ControleAcessoTeste.java
    - name: Executando no JAVA
      run: |
           cd src
           java -cp . ControleAcessoTeste
           
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Buildando  Docker image
      with:
        image: viniciustech/catraca
        tags: ${{ github.run_number }}, ${{ steps.gerador.outputs.version }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

